apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dxc-dashboard-prod
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/tomodachi0/dxc-ops-deployment-dashboard/backend
    newTag: main-ad67375
  - name: ghcr.io/tomodachi0/dxc-ops-deployment-dashboard/frontend
    newTag: main-ad67375