apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dxc-dashboard-prod
resources:
  - ../../base
  - ingress.yaml
images:
  - name: dxcopsacr.azurecr.io/dxc-ops-backend
    newTag: main-ad67375
  - name: dxcopsacr.azurecr.io/dxc-ops-frontend
    newTag: main-ad67375