apiVersion: apps/v1
kind: Deployment
metadata:
  name: dxc-frontend
  namespace: dxc-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dxc-frontend
  template:
    metadata:
      labels:
        app: dxc-frontend
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: frontend
          image: dxcopsacr.azurecr.io/dxc-ops-frontend:placeholder
          ports:
            - containerPort: 80