apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-pvc.yaml
  - backend-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml