apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dxc-dashboard-dev
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/tomodachi0/dxc-ops-deployment-dashboard/backend
    newTag: dev-5a54f71
  - name: ghcr.io/tomodachi0/dxc-ops-deployment-dashboard/frontend
    newTag: dev-5a54f71