name: CI

on:
  pull_request:
    branches: [main]


jobs:
  all:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Lint code
        run: flake8 .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install pytest httpx

      - name: Run tests
        run: backend/pytest

      - name: Build backend image
        run: docker build -t dxc-backend:ci-test ./backend

      - name: Build frontend image
        run: docker build -t dxc-frontend:ci-test ./frontend




